### PR TITLE
Design Teardown Project completed

### PR DESCRIPTION
**Pull request by mkezfarias**
Hi, I completed the 5th HTML and CSS project, design teardown. Since I'm not currenrly partnered, Willow Mata from student success instructed me on submitting projects on my own and let you guys know about my situation.

Thanks have a great day :dancing_men:

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi mkezmkez! good job,

Just one update we have to make on your html document: 

- [x] Please, wrap each article in your html document with an ```<article> tag``` :slightly_smiling_face: 

After the update submit another form for code review.

#### ``` Have a great day``` :slightly_smiling_face:

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Great project by all standards TEAM,👋
You have successfully implemented the changes suggested by my colleagues.
I like the work you guys put into this project💪. I nearly approved your work but currently, there is one HTML validation failure.🙂🙂
This is because you did not specify the character encoding in the head of your Html file🙂🙂
# Add this line ```<meta charset="UTF-8" />``` and submit for review
Trust me you are 99% through
Happy coding🙂🙂

**Comment by mkezfarias** [comment]
Add  <meta charset="UTF-8"> tag as requested

**Review by Forison — COMMENTED** [review]
# pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Good Job Team👋👋
## Project looks Awesome👌👌 
### Go ahead and merge to master
# Project approved
Happy coding😇😇😇

**Pull request merged**
